//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ResX Guard.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResX.Guard", "0.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        internal Resources() { }
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager("SampleProject.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }
        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        /// <summary>Confirms (Neutral)</summary>
        /// <summary>Confirm (pt)</summary>
        internal static string Confirms {
            get { return ResourceManager.GetString("Confirms", resourceCulture); }
        }

        /// <summary>Import failed: {0} (Neutral)</summary>
        /// <summary>Falha na importação: {0} (pt)</summary>
        internal static string ImportFailedEror {
            get { return ResourceManager.GetString("ImportFailedEror", resourceCulture); }
        }

        /// <summary>Project has no resource file (Neutral)</summary>
        /// <summary>O projeto não tem ficheiro de recursos. (pt)</summary>
        internal static string ProjectHasNoResourceFile {
            get { return ResourceManager.GetString("ProjectHasNoResourceFile", resourceCulture); }
        }

        /// <summary>Welcome to ResX Guard (Neutral)</summary>
        /// <summary>Bem-vindo ao ResX Guard (pt)</summary>
        internal static string WelcomeMessage {
            get { return ResourceManager.GetString("WelcomeMessage", resourceCulture); }
        }

    }
}
