//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ResX Guard.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by ResX Guard / StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then regenerate.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResX.Guard", "0.2.1")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Line one Line two.
        /// </summary>
        /// <remarks>
        ///   Neutral: Line one Line two
        ///   pt: Linha um Linha dois
        /// </remarks>
        internal static string AddressLine {
            get {
                return ResourceManager.GetString("AddressLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        /// <remarks>
        ///   Neutral: Cancel
        ///   pt: Cancelar
        /// </remarks>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirms.
        /// </summary>
        /// <remarks>
        ///   Neutral: Confirms
        ///   pt: Confirm
        /// </remarks>
        internal static string Confirms {
            get {
                return ResourceManager.GetString("Confirms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete file?.
        /// </summary>
        /// <remarks>
        ///   Neutral: Delete file?
        ///   pt: Eliminar ficheiro?
        /// </remarks>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export completed successfully..
        /// </summary>
        /// <remarks>
        ///   Neutral: Export completed successfully.
        ///   pt: Exportação concluída com sucesso.
        /// </remarks>
        internal static string ExportComplete {
            get {
                return ResourceManager.GetString("ExportComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press F1 for help.
        /// </summary>
        /// <remarks>
        ///   Neutral: Press F1 for help
        ///   pt: Prima F1 para ajuda
        /// </remarks>
        internal static string HelpHint {
            get {
                return ResourceManager.GetString("HelpHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import failed: {0}.
        /// </summary>
        /// <remarks>
        ///   Neutral: Import failed: {0}
        ///   pt: Falha na importação: {0}
        /// </remarks>
        internal static string ImportFailedEror {
            get {
                return ResourceManager.GetString("ImportFailedEror", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} items found.
        /// </summary>
        /// <remarks>
        ///   Neutral: {0} items found
        ///   pt: {0} itens encontrados
        /// </remarks>
        internal static string ItemsFound {
            get {
                return ResourceManager.GetString("ItemsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} items found.
        /// </summary>
        /// <remarks>
        ///   Neutral: {0} items found
        ///   pt: Encontrados itens
        /// </remarks>
        internal static string ItemsFoundBad {
            get {
                return ResourceManager.GetString("ItemsFoundBad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A very long key for layout testing.
        /// </summary>
        /// <remarks>
        ///   Neutral: A very long key for layout testing
        ///   pt: Uma chave muito longa para testar o layout
        /// </remarks>
        internal static string LongKeyThatShouldNotBreakTheSummaryPanelLayoutWhenDisplayed {
            get {
                return ResourceManager.GetString("LongKeyThatShouldNotBreakTheSummaryPanelLayoutWhenDisplayed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        /// <remarks>
        ///   Neutral: Open settings
        ///   pt: (missing)
        /// </remarks>
        internal static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project has no resource file.
        /// </summary>
        /// <remarks>
        ///   Neutral: Project has no resource file
        ///   pt: O projeto não tem ficheiro de recursos.
        /// </remarks>
        internal static string ProjectHasNoResourceFile {
            get {
                return ResourceManager.GetString("ProjectHasNoResourceFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        /// <remarks>
        ///   Neutral: Save changes
        ///   pt: Guardar alterações
        /// </remarks>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to untitled.
        /// </summary>
        /// <remarks>
        ///   Neutral: untitled
        ///   pt: sem título
        /// </remarks>
        internal static string untitled_key {
            get {
                return ResourceManager.GetString("untitled_key", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to ResX Guard.
        /// </summary>
        /// <remarks>
        ///   Neutral: Welcome to ResX Guard
        ///   pt: Bem-vindo ao ResX Guard
        /// </remarks>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
