//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ResX Guard.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by ResX Guard / StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then regenerate.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResX.Guard", "0.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to ResX Guard.
        /// </summary>
        /// <remarks>
        ///   Neutral: Welcome to ResX Guard
        ///   en: (missing)
        ///   pt: Bem-vindo ao ResX Guard
        /// </remarks>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project has no resource file.
        /// </summary>
        /// <remarks>
        ///   Neutral: Project has no resource file
        ///   en: (missing)
        ///   pt: O projeto não tem ficheiro de recursos.
        /// </remarks>
        internal static string ProjectHasNoResourceFile {
            get {
                return ResourceManager.GetString("ProjectHasNoResourceFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import failed: {0}.
        /// </summary>
        /// <remarks>
        ///   Neutral: Import failed: {0}
        ///   en: (missing)
        ///   pt: Falha na importação: {0}
        /// </remarks>
        internal static string ImportFailedEror {
            get {
                return ResourceManager.GetString("ImportFailedEror", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirms.
        /// </summary>
        /// <remarks>
        ///   Neutral: Confirms
        ///   en: (missing)
        ///   pt: Confirm
        /// </remarks>
        internal static string Confirms {
            get {
                return ResourceManager.GetString("Confirms", resourceCulture);
            }
        }
    }
}
