import { describe, expect, it } from 'vitest';
import { generateDesignerCs } from '../src/services/designer-generator';

describe('designer generator', () => {
  it('emits auto-generated strongly typed resources', () => {
    const cs = generateDesignerCs({
      className: 'Resources',
      namespace: 'SampleProject',
      isPublic: false,
      resourceBaseName: 'SampleProject.Properties.Resources',
      entries: [
        { key: 'SaveFailed', value: 'Save failed.', comment: '' },
        { key: 'Hello', value: 'Hello', comment: '' },
      ],
    });

    expect(cs).toContain('<auto-generated>');
    expect(cs).toContain('namespace SampleProject');
    expect(cs).toContain('internal class Resources');
    expect(cs).toContain('static string SaveFailed');
    expect(cs).toContain('SampleProject.Properties.Resources');
  });

  it('supports public generator', () => {
    const cs = generateDesignerCs({
      className: 'Resources',
      namespace: 'SampleProject',
      isPublic: true,
      resourceBaseName: 'SampleProject.Resources',
      entries: [{ key: 'A', value: 'a', comment: '' }],
    });
    expect(cs).toContain('public class Resources');
    expect(cs).toContain('public static string A');
  });
});
