import { describe, expect, it } from 'vitest';
import { generateDesignerCs } from '../src/services/designer-generator';

describe('designer generator', () => {
  it('emits auto-generated strongly typed resources', () => {
    const cs = generateDesignerCs({
      className: 'Resources',
      namespace: 'SampleProject',
      isPublic: false,
      resourceBaseName: 'SampleProject.Properties.Resources',
      entries: [
        {
          key: 'SaveFailed',
          comment: '',
          translations: { '': 'Save failed.', pt: 'Falha ao guardar.' },
        },
        { key: 'Hello', comment: '', translations: { '': 'Hello', pt: 'Olá' } },
      ],
      locales: ['', 'pt'],
    });

    expect(cs).toContain('<auto-generated>');
    expect(cs).toContain('namespace SampleProject');
    expect(cs).toContain('internal class Resources');
    expect(cs).toContain('static string SaveFailed');
    expect(cs).toContain('SampleProject.Properties.Resources');
    expect(cs).toContain('Neutral: Save failed.');
    expect(cs).toContain('pt: Falha ao guardar.');
    expect(cs).toContain('pt: Olá');
  });

  it('marks missing translations in remarks', () => {
    const cs = generateDesignerCs({
      className: 'Resources',
      namespace: 'SampleProject',
      isPublic: false,
      resourceBaseName: 'SampleProject.Resources',
      entries: [
        { key: 'EmptyValueWarning', comment: '', translations: { '': 'Value cannot be empty.' } },
      ],
      locales: ['', 'pt'],
    });
    expect(cs).toContain('Neutral: Value cannot be empty.');
    expect(cs).toContain('pt: (missing)');
  });

  it('supports public generator', () => {
    const cs = generateDesignerCs({
      className: 'Resources',
      namespace: 'SampleProject',
      isPublic: true,
      resourceBaseName: 'SampleProject.Resources',
      entries: [{ key: 'A', comment: '', translations: { '': 'a' } }],
    });
    expect(cs).toContain('public class Resources');
    expect(cs).toContain('public static string A');
  });
});
