import * as fs from 'fs/promises';
import * as path from 'path';
import { NEUTRAL_LOCALE, type ResxFile } from '../models/types';

export interface DesignerEntry {
  key: string;
  comment: string;
  /** locale → value. Empty string is Neutral. */
  translations: Record<string, string>;
}

export interface DesignerOptions {
  className: string;
  namespace: string;
  /** public vs internal access */
  isPublic: boolean;
  resourceBaseName: string;
  entries: DesignerEntry[];
  /** Locale order for XML docs (Neutral first). */
  locales?: string[];
}

const AUTO_GENERATED_MARKER = '<auto-generated>';

export async function shouldUpdateDesigner(designerPath: string): Promise<boolean> {
  try {
    const content = await fs.readFile(designerPath, 'utf8');
    return content.includes(AUTO_GENERATED_MARKER) || content.includes('Auto-Generated');
  } catch {
    // File does not exist — safe to create
    return true;
  }
}

export function generateDesignerCs(options: DesignerOptions): string {
  const access = options.isPublic ? 'public' : 'internal';
  const locales = options.locales ?? collectLocales(options.entries);
  const props = options.entries
    .filter((e) => isValidIdentifier(e.key))
    .map((e) => propertyBlock(e, access, locales))
    .join('\n\n');

  return `//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ResX Guard.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ${options.namespace} {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by ResX Guard / StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then regenerate.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResX.Guard", "0.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    ${access} class ${options.className} {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        ${access === 'public' ? 'internal' : 'internal'} ${options.className}() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        ${access} static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("${options.resourceBaseName}", typeof(${options.className}).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        ${access} static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

${props}
    }
}
`;
}

export async function writeDesignerCs(
  designerPath: string,
  options: DesignerOptions
): Promise<boolean> {
  if (!(await shouldUpdateDesigner(designerPath))) {
    return false;
  }
  const content = generateDesignerCs(options);
  await fs.mkdir(path.dirname(designerPath), { recursive: true });
  await fs.writeFile(designerPath, content, 'utf8');
  return true;
}

export async function resolveDesignerMeta(
  neutralResxPath: string
): Promise<{
  designerPath: string;
  className: string;
  namespace: string;
  isPublic: boolean;
  resourceBaseName: string;
}> {
  const dir = path.dirname(neutralResxPath);
  const base = path.basename(neutralResxPath, '.resx');
  const className = sanitizeIdentifier(base);
  const designerPath = path.join(dir, `${base}.Designer.cs`);

  let isPublic = false;
  let rootNamespace = guessNamespace(dir);

  const csproj = await findCsproj(dir);
  if (csproj) {
    try {
      const xml = await fs.readFile(csproj, 'utf8');
      if (/PublicResXFileCodeGenerator/i.test(xml)) {
        isPublic = true;
      }
      rootNamespace = parseRootNamespace(xml, csproj);
      const projectDir = path.dirname(csproj);
      const relDir = path.relative(projectDir, dir);
      const relFile = path.relative(projectDir, neutralResxPath);
      const custom = parseCustomToolNamespace(xml, relFile);
      const typeNamespace = custom || designerTypeNamespace(rootNamespace, relDir);
      const resourceBaseName = resourceManagerName(typeNamespace, base);
      return {
        designerPath,
        className,
        namespace: typeNamespace,
        isPublic,
        resourceBaseName,
      };
    } catch {
      // fall through
    }
  }

  return {
    designerPath,
    className,
    namespace: rootNamespace,
    isPublic,
    resourceBaseName: resourceManagerName(rootNamespace, base),
  };
}

/** C# namespace for a .resx: RootNamespace + relative folders (Visual Studio / SDK default). */
export function designerTypeNamespace(rootNamespace: string, relativeDir: string): string {
  if (!relativeDir || relativeDir === '.') {
    return rootNamespace;
  }
  const segs = relativeDir
    .split(/[/\\]/)
    .filter((s) => s && s !== '.')
    .map((s) => sanitizeIdentifier(s));
  if (segs.length === 0) {
    return rootNamespace;
  }
  const suffix = segs.join('.');
  const root = rootNamespace.toLowerCase();
  const suf = suffix.toLowerCase();
  if (root === suf || root.endsWith(`.${suf}`)) {
    return rootNamespace;
  }
  return `${rootNamespace}.${suffix}`;
}

function resourceManagerName(typeNamespace: string, className: string): string {
  return `${typeNamespace}.${className}`;
}

function parseRootNamespace(csprojXml: string, csprojPath: string): string {
  const nsMatch = csprojXml.match(/<RootNamespace>\s*([^<]+?)\s*<\/RootNamespace>/i);
  if (nsMatch) {
    return nsMatch[1].trim();
  }
  const nameMatch = csprojXml.match(/<AssemblyName>\s*([^<]+?)\s*<\/AssemblyName>/i);
  if (nameMatch) {
    return nameMatch[1].trim();
  }
  return path.basename(csprojPath, '.csproj');
}

function parseCustomToolNamespace(csprojXml: string, resxRelFromProject: string): string | undefined {
  const normalized = resxRelFromProject.replace(/\\/g, '/');
  const escaped = normalized.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\//g, '[\\\\/]');
  const re = new RegExp(
    `<EmbeddedResource[^>]*Update="${escaped}"[^>]*>([\\s\\S]*?)</EmbeddedResource>`,
    'i'
  );
  const block = csprojXml.match(re);
  const custom = block?.[1]?.match(/<CustomToolNamespace>\s*([^<]+?)\s*<\/CustomToolNamespace>/i);
  return custom?.[1]?.trim();
}

function guessNamespace(dir: string): string {
  const parts = dir.split(/[/\\]/).filter(Boolean);
  // Use last 1-2 folder segments
  if (parts.length >= 2) {
    return sanitizeIdentifier(parts[parts.length - 2]);
  }
  return 'Resources';
}

async function findCsproj(startDir: string): Promise<string | null> {
  let current = startDir;
  for (let i = 0; i < 6; i++) {
    try {
      const entries = await fs.readdir(current);
      const csproj = entries.find((e) => e.endsWith('.csproj'));
      if (csproj) {
        return path.join(current, csproj);
      }
    } catch {
      return null;
    }
    const parent = path.dirname(current);
    if (parent === current) {
      break;
    }
    current = parent;
  }
  return null;
}

export function buildDesignerEntries(files: ResxFile[]): DesignerEntry[] {
  const ordered = [...files].sort((a, b) => compareLocales(a.locale, b.locale));
  const byKey = new Map<string, DesignerEntry>();
  const order: string[] = [];

  for (const file of ordered) {
    for (const entry of file.entries) {
      let item = byKey.get(entry.key);
      if (!item) {
        item = { key: entry.key, comment: entry.comment, translations: {} };
        byKey.set(entry.key, item);
        order.push(entry.key);
      }
      item.translations[file.locale] = entry.value;
      if (file.locale === NEUTRAL_LOCALE) {
        item.comment = entry.comment;
      }
    }
  }

  return order.map((key) => byKey.get(key)!);
}

function propertyBlock(entry: DesignerEntry, access: string, locales: string[]): string {
  const neutral = entry.translations[NEUTRAL_LOCALE] ?? firstValue(entry.translations);
  const summary = escapeXml(truncate(neutral));
  const remarks = locales
    .map((locale) => {
      const raw = entry.translations[locale];
      const text = raw === undefined || raw === '' ? '(missing)' : raw;
      return `        ///   ${designerLocaleLabel(locale)}: ${escapeXml(truncate(text, 120))}`;
    })
    .join('\n');

  return `        /// <summary>
        ///   Looks up a localized string similar to ${summary}.
        /// </summary>
        /// <remarks>
${remarks}
        /// </remarks>
        ${access} static string ${entry.key} {
            get {
                return ResourceManager.GetString("${entry.key}", resourceCulture);
            }
        }`;
}

function collectLocales(entries: DesignerEntry[]): string[] {
  const set = new Set<string>();
  for (const entry of entries) {
    for (const locale of Object.keys(entry.translations)) {
      set.add(locale);
    }
  }
  return [...set].sort(compareLocales);
}

function compareLocales(a: string, b: string): number {
  if (a === NEUTRAL_LOCALE) {
    return -1;
  }
  if (b === NEUTRAL_LOCALE) {
    return 1;
  }
  return a.localeCompare(b);
}

function designerLocaleLabel(locale: string): string {
  return locale === NEUTRAL_LOCALE || locale === '' ? 'Neutral' : locale;
}

function firstValue(translations: Record<string, string>): string {
  return Object.values(translations).find((v) => v) ?? '';
}

function truncate(text: string, max = 80): string {
  if (text.length <= max) {
    return text;
  }
  return text.slice(0, max - 3) + '...';
}

function isValidIdentifier(name: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name);
}

function sanitizeIdentifier(name: string): string {
  let cleaned = name.replace(/[^A-Za-z0-9_]/g, '_');
  if (!cleaned) {
    cleaned = 'Resources';
  }
  if (/^[0-9]/.test(cleaned)) {
    cleaned = '_' + cleaned;
  }
  return cleaned;
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/\r?\n/g, ' ');
}
