import * as fs from 'fs/promises';
import * as path from 'path';
import type { ResxEntry } from '../models/types';

export interface DesignerOptions {
  className: string;
  namespace: string;
  /** public vs internal access */
  isPublic: boolean;
  resourceBaseName: string;
  entries: ResxEntry[];
}

const AUTO_GENERATED_MARKER = '<auto-generated>';

export async function shouldUpdateDesigner(designerPath: string): Promise<boolean> {
  try {
    const content = await fs.readFile(designerPath, 'utf8');
    return content.includes(AUTO_GENERATED_MARKER) || content.includes('Auto-Generated');
  } catch {
    // File does not exist — safe to create
    return true;
  }
}

export function generateDesignerCs(options: DesignerOptions): string {
  const access = options.isPublic ? 'public' : 'internal';
  const props = options.entries
    .filter((e) => isValidIdentifier(e.key))
    .map((e) => {
      const summary = escapeXml(e.value.length > 80 ? e.value.slice(0, 77) + '...' : e.value);
      return `        /// <summary>
        ///   Looks up a localized string similar to ${summary}.
        /// </summary>
        ${access} static string ${e.key} {
            get {
                return ResourceManager.GetString("${e.key}", resourceCulture);
            }
        }`;
    })
    .join('\n\n');

  return `//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ResX Guard.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ${options.namespace} {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by ResX Guard / StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then regenerate.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResX.Guard", "0.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    ${access} class ${options.className} {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        ${access === 'public' ? 'internal' : 'internal'} ${options.className}() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        ${access} static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("${options.resourceBaseName}", typeof(${options.className}).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        ${access} static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

${props}
    }
}
`;
}

export async function writeDesignerCs(
  designerPath: string,
  options: DesignerOptions
): Promise<boolean> {
  if (!(await shouldUpdateDesigner(designerPath))) {
    return false;
  }
  const content = generateDesignerCs(options);
  await fs.mkdir(path.dirname(designerPath), { recursive: true });
  await fs.writeFile(designerPath, content, 'utf8');
  return true;
}

export async function resolveDesignerMeta(
  neutralResxPath: string
): Promise<{
  designerPath: string;
  className: string;
  namespace: string;
  isPublic: boolean;
  resourceBaseName: string;
}> {
  const dir = path.dirname(neutralResxPath);
  const base = path.basename(neutralResxPath, '.resx');
  const designerPath = path.join(dir, `${base}.Designer.cs`);

  let isPublic = false;
  let namespace = guessNamespace(dir);
  let className = sanitizeIdentifier(base);

  // Look for nearby .csproj
  const csproj = await findCsproj(dir);
  if (csproj) {
    try {
      const xml = await fs.readFile(csproj, 'utf8');
      if (/PublicResXFileCodeGenerator/i.test(xml)) {
        isPublic = true;
      }
      const nsMatch = xml.match(/<RootNamespace>([^<]+)<\/RootNamespace>/i);
      if (nsMatch) {
        namespace = nsMatch[1].trim();
      } else {
        const nameMatch = xml.match(/<AssemblyName>([^<]+)<\/AssemblyName>/i);
        if (nameMatch) {
          namespace = nameMatch[1].trim();
        } else {
          namespace = path.basename(csproj, '.csproj');
        }
      }

      // Embedded resource name is typically RootNamespace.Folder.File
      const projectDir = path.dirname(csproj);
      const rel = path.relative(projectDir, dir);
      const parts = [namespace];
      if (rel && rel !== '.') {
        parts.push(...rel.split(/[/\\]/).filter(Boolean));
      }
      parts.push(base);
      return {
        designerPath,
        className,
        namespace: namespaceIncludesFolder(namespace, rel) ? namespace : namespace,
        isPublic,
        resourceBaseName: parts.join('.'),
      };
    } catch {
      // fall through
    }
  }

  return {
    designerPath,
    className,
    namespace,
    isPublic,
    resourceBaseName: `${namespace}.${base}`,
  };
}

function namespaceIncludesFolder(_ns: string, _rel: string): boolean {
  return false;
}

function guessNamespace(dir: string): string {
  const parts = dir.split(/[/\\]/).filter(Boolean);
  // Use last 1-2 folder segments
  if (parts.length >= 2) {
    return sanitizeIdentifier(parts[parts.length - 2]);
  }
  return 'Resources';
}

async function findCsproj(startDir: string): Promise<string | null> {
  let current = startDir;
  for (let i = 0; i < 6; i++) {
    try {
      const entries = await fs.readdir(current);
      const csproj = entries.find((e) => e.endsWith('.csproj'));
      if (csproj) {
        return path.join(current, csproj);
      }
    } catch {
      return null;
    }
    const parent = path.dirname(current);
    if (parent === current) {
      break;
    }
    current = parent;
  }
  return null;
}

function isValidIdentifier(name: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name);
}

function sanitizeIdentifier(name: string): string {
  let cleaned = name.replace(/[^A-Za-z0-9_]/g, '_');
  if (!cleaned) {
    cleaned = 'Resources';
  }
  if (/^[0-9]/.test(cleaned)) {
    cleaned = '_' + cleaned;
  }
  return cleaned;
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/\r?\n/g, ' ');
}
