using ResXGuard.Core;

namespace ResXGuard.Core.Tests;

public class FixtureIntegrationTests
{
    private static readonly string FixtureRoot = Path.GetFullPath(
        Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "..", "fixtures", "sample-project"));

    [Fact]
    public async Task Loads_sample_project_families()
    {
        var neutral = Path.Combine(FixtureRoot, "Properties", "Resources.resx");
        var pt = Path.Combine(FixtureRoot, "Properties", "Resources.pt.resx");
        Assert.True(File.Exists(neutral));
        Assert.True(File.Exists(pt));

        var scanned = WorkspaceScanner.GroupResxFiles(
            new[] { neutral, pt },
            new[] { new WorkspaceFolder { Name = "SampleProject", FsPath = FixtureRoot } });

        Assert.NotEmpty(scanned.Families);
        var family = scanned.Families[0];
        var files = new List<ResxFile>();
        foreach (var path in family.Files.Values)
            files.Add(await ResxParser.ParseResxFileAsync(path));

        var rows = ValidationEngine.BuildRows(family, files);
        Assert.NotEmpty(rows);
        var issues = ValidationEngine.ValidateFamily(family, files, new ValidationRulesConfig());
        Assert.NotNull(issues);
    }
}

public class NamingTests
{
    [Fact]
    public void ToPascalCaseKey_converts_phrases()
    {
        Assert.Equal("InvalidResourceFile", Naming.ToPascalCaseKey("Invalid resource file:"));
        Assert.Equal("SaveFailed", Naming.ToPascalCaseKey("Save failed."));
    }
}

public class DesignerTests
{
    [Fact]
    public void GenerateDesignerCs_includes_version()
    {
        var cs = DesignerGenerator.GenerateDesignerCs(new DesignerOptions
        {
            ClassName = "Resources",
            Namespace = "SampleProject",
            ResourceBaseName = "SampleProject.Resources",
            Entries = new List<DesignerEntry>
            {
                new() { Key = "Hello", Translations = new Dictionary<string, string> { [""] = "Hi" } }
            }
        });
        Assert.Contains("<auto-generated>", cs);
        Assert.Contains(VersionInfo.ExtensionVersion, cs);
        Assert.Contains("static string Hello", cs);
    }
}
