import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'version.json'), 'utf8'));
const [major, minor, patch] = version.split('.').map(Number);

function setPackageVersion(pkgPath) {
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
    pkg.version = version;
    writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
  } catch {
    // package not yet created
  }
}

function setVsixManifestVersion(manifestPath) {
  try {
    let manifest = readFileSync(manifestPath, 'utf8');
    manifest = manifest.replace(
      /(<Identity Id="[^"]+" Version=")[^"]+(")/,
      `$1${version}$2`
    );
    writeFileSync(manifestPath, manifest);
  } catch {
    // VS extension not yet created
  }
}

setPackageVersion(join(root, 'package.json'));
setPackageVersion(join(root, 'packages', 'core-ts', 'package.json'));
setPackageVersion(join(root, 'packages', 'ui', 'package.json'));
setPackageVersion(join(root, 'apps', 'vscode', 'package.json'));

// packages/core-ts/src/version.ts
const coreVersionPath = join(root, 'packages', 'core-ts', 'src', 'version.ts');
mkdirSync(dirname(coreVersionPath), { recursive: true });
writeFileSync(
  coreVersionPath,
  `/** Auto-generated by scripts/sync-version.mjs — do not edit */\nexport const EXTENSION_VERSION = '${version}';\n`
);

// packages/ui — Vite env file
const uiEnvPath = join(root, 'packages', 'ui', '.env.build');
mkdirSync(dirname(uiEnvPath), { recursive: true });
writeFileSync(uiEnvPath, `VITE_EXTENSION_VERSION=${version}\n`);

// Visual Studio Directory.Build.props
const vsPropsPath = join(root, 'apps', 'visualstudio', 'Directory.Build.props');
mkdirSync(dirname(vsPropsPath), { recursive: true });
writeFileSync(
  vsPropsPath,
  `<Project>
  <PropertyGroup>
    <Version>${version}</Version>
    <AssemblyVersion>${major}.${minor}.0.0</AssemblyVersion>
    <FileVersion>${major}.${minor}.${patch}.0</FileVersion>
    <InformationalVersion>${version}</InformationalVersion>
  </PropertyGroup>
</Project>
`
);

// C# core Version.cs
const csharpVersionPath = join(root, 'apps', 'visualstudio', 'ResXGuard.Core', 'Version.cs');
mkdirSync(dirname(csharpVersionPath), { recursive: true });
writeFileSync(
  csharpVersionPath,
  `namespace ResXGuard.Core;\n\n/// <summary>Auto-generated by scripts/sync-version.mjs — do not edit.</summary>\npublic static class VersionInfo\n{\n    public const string ExtensionVersion = "${version}";\n}\n`
);

const vsDir = join(root, 'apps', 'visualstudio', 'ResXGuard');
setVsixManifestVersion(join(vsDir, 'source.extension.vsixmanifest'));
setVsixManifestVersion(join(vsDir, 'extension.vsixmanifest'));

console.log(`Synced version ${version}`);
