import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'version.json'), 'utf8'));
const [major, minor, patch] = version.split('.').map(Number);

// apps/vscode/package.json
const vscodePkgPath = join(root, 'apps', 'vscode', 'package.json');
try {
  const vscodePkg = JSON.parse(readFileSync(vscodePkgPath, 'utf8'));
  vscodePkg.version = version;
  writeFileSync(vscodePkgPath, JSON.stringify(vscodePkg, null, 2) + '\n');
} catch {
  // vscode app not yet created
}

// packages/core-ts/src/version.ts
const coreVersionPath = join(root, 'packages', 'core-ts', 'src', 'version.ts');
mkdirSync(dirname(coreVersionPath), { recursive: true });
writeFileSync(
  coreVersionPath,
  `/** Auto-generated by scripts/sync-version.mjs — do not edit */\nexport const EXTENSION_VERSION = '${version}';\n`
);

// packages/ui — Vite env file
const uiEnvPath = join(root, 'packages', 'ui', '.env.build');
mkdirSync(dirname(uiEnvPath), { recursive: true });
writeFileSync(uiEnvPath, `VITE_EXTENSION_VERSION=${version}\n`);

// Visual Studio Directory.Build.props
const vsPropsPath = join(root, 'apps', 'visualstudio', 'Directory.Build.props');
mkdirSync(dirname(vsPropsPath), { recursive: true });
writeFileSync(
  vsPropsPath,
  `<Project>
  <PropertyGroup>
    <Version>${version}</Version>
    <AssemblyVersion>${major}.${minor}.0.0</AssemblyVersion>
    <FileVersion>${major}.${minor}.${patch}.0</FileVersion>
    <InformationalVersion>${version}</InformationalVersion>
  </PropertyGroup>
</Project>
`
);

// C# core Version.cs
const csharpVersionPath = join(root, 'apps', 'visualstudio', 'ResXGuard.Core', 'Version.cs');
mkdirSync(dirname(csharpVersionPath), { recursive: true });
writeFileSync(
  csharpVersionPath,
  `namespace ResXGuard.Core;\n\n/// <summary>Auto-generated by scripts/sync-version.mjs — do not edit.</summary>\npublic static class VersionInfo\n{\n    public const string ExtensionVersion = "${version}";\n}\n`
);

console.log(`Synced version ${version}`);
