using System.Text;
using System.Text.RegularExpressions;

namespace ResXGuard.Core;

public sealed class DesignerEntry
{
    public string Key { get; init; } = "";
    public string Comment { get; init; } = "";
    public Dictionary<string, string> Translations { get; init; } = new();
}

public sealed class DesignerOptions
{
    public string ClassName { get; init; } = "";
    public string Namespace { get; init; } = "";
    public bool IsPublic { get; init; }
    public string ResourceBaseName { get; init; } = "";
    public List<DesignerEntry> Entries { get; init; } = new();
    public List<string>? Locales { get; init; }
}

public static class DesignerGenerator
{
    private static readonly Regex IdentifierRegex = new(@"^[a-zA-Z_][a-zA-Z0-9_]*$", RegexOptions.Compiled);

    public static Task<bool> ShouldUpdateDesignerAsync(string designerPath, CancellationToken ct = default) =>
        Task.Run(() =>
        {
            try
            {
                var content = File.ReadAllText(designerPath);
                return content.IndexOf("<auto-generated>", StringComparison.OrdinalIgnoreCase) >= 0
                    || content.IndexOf("Auto-Generated", StringComparison.OrdinalIgnoreCase) >= 0;
            }
            catch
            {
                return true;
            }
        }, ct);

    public static string GenerateDesignerCs(DesignerOptions options)
    {
        var access = options.IsPublic ? "public" : "internal";
        var locales = options.Locales ?? CollectLocales(options.Entries);
        var sb = new StringBuilder();
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by ResX Guard.");
        sb.AppendLine("//     Runtime Version:4.0.30319.42000");
        sb.AppendLine("//");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine($"namespace {options.Namespace} {{");
        sb.AppendLine("    using System;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///   A strongly-typed resource class, for looking up localized strings, etc.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"ResX.Guard\", \"{VersionInfo.ExtensionVersion}\")]");
        sb.AppendLine("    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]");
        sb.AppendLine($"    {access} class {options.ClassName} {{");
        sb.AppendLine("        private static global::System.Resources.ResourceManager resourceMan;");
        sb.AppendLine("        private static global::System.Globalization.CultureInfo resourceCulture;");
        sb.AppendLine($"        internal {options.ClassName}() {{ }}");
        sb.AppendLine($"        {access} static global::System.Resources.ResourceManager ResourceManager {{");
        sb.AppendLine("            get {");
        sb.AppendLine("                if (object.ReferenceEquals(resourceMan, null)) {");
        sb.AppendLine($"                    resourceMan = new global::System.Resources.ResourceManager(\"{options.ResourceBaseName}\", typeof({options.ClassName}).Assembly);");
        sb.AppendLine("                }");
        sb.AppendLine("                return resourceMan;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine($"        {access} static global::System.Globalization.CultureInfo Culture {{");
        sb.AppendLine("            get { return resourceCulture; }");
        sb.AppendLine("            set { resourceCulture = value; }");
        sb.AppendLine("        }");
        foreach (var entry in options.Entries.Where(e => IsValidIdentifier(e.Key)))
            sb.AppendLine(PropertyBlock(entry, access, locales));
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static Task<bool> WriteDesignerCsAsync(string designerPath, DesignerOptions options, CancellationToken ct = default) =>
        Task.Run(async () =>
        {
            if (!await ShouldUpdateDesignerAsync(designerPath, ct).ConfigureAwait(false))
                return false;
            var content = GenerateDesignerCs(options);
            Directory.CreateDirectory(Path.GetDirectoryName(designerPath)!);
            File.WriteAllText(designerPath, content, Encoding.UTF8);
            return true;
        }, ct);

    public static Task<DesignerMeta> ResolveDesignerMetaAsync(string neutralResxPath, CancellationToken ct = default) =>
        Task.Run(() =>
        {
            ct.ThrowIfCancellationRequested();
            var dir = Path.GetDirectoryName(neutralResxPath)!;
            var baseName = Path.GetFileNameWithoutExtension(neutralResxPath);
            var className = SanitizeIdentifier(baseName);
            var designerPath = Path.Combine(dir, $"{baseName}.Designer.cs");
            var isPublic = false;
            var rootNamespace = GuessNamespace(dir);

            var csproj = FindCsproj(dir);
            if (csproj != null)
            {
                try
                {
                    var xml = File.ReadAllText(csproj);
                    if (Regex.IsMatch(xml, "PublicResXFileCodeGenerator", RegexOptions.IgnoreCase))
                        isPublic = true;
                    rootNamespace = ParseRootNamespace(xml, csproj);
                    var projectDir = Path.GetDirectoryName(csproj)!;
                    var relDir = RelativePath(projectDir, dir);
                    var relFile = RelativePath(projectDir, neutralResxPath);
                    var custom = ParseCustomToolNamespace(xml, relFile);
                    var typeNamespace = custom ?? DesignerTypeNamespace(rootNamespace, relDir);
                    return new DesignerMeta
                    {
                        DesignerPath = designerPath,
                        ClassName = className,
                        Namespace = typeNamespace,
                        IsPublic = isPublic,
                        ResourceBaseName = ResourceManagerName(typeNamespace, baseName)
                    };
                }
                catch { /* fall through */ }
            }

            return new DesignerMeta
            {
                DesignerPath = designerPath,
                ClassName = className,
                Namespace = rootNamespace,
                IsPublic = isPublic,
                ResourceBaseName = ResourceManagerName(rootNamespace, baseName)
            };
        }, ct);

    public static string DesignerTypeNamespace(string rootNamespace, string relativeDir)
    {
        if (string.IsNullOrEmpty(relativeDir) || relativeDir == ".") return rootNamespace;
        var segs = relativeDir.Split('/', '\\')
            .Where(s => !string.IsNullOrEmpty(s) && s != ".")
            .Select(SanitizeIdentifier)
            .Where(s => !string.IsNullOrEmpty(s))
            .ToList();
        if (segs.Count == 0) return rootNamespace;
        var suffix = string.Join(".", segs);
        var root = rootNamespace.ToLowerInvariant();
        var suf = suffix.ToLowerInvariant();
        if (root == suf || root.EndsWith("." + suf, StringComparison.OrdinalIgnoreCase)) return rootNamespace;
        return $"{rootNamespace}.{suffix}";
    }

    public static List<DesignerEntry> BuildDesignerEntries(IReadOnlyList<ResourceRow> rows, IReadOnlyList<string> locales)
    {
        return rows.Select(row => new DesignerEntry
        {
            Key = row.Key,
            Comment = row.Comment,
            Translations = locales.ToDictionary(
                l => l,
                l => row.Values.TryGetValue(l, out var v) ? v : "")
        }).ToList();
    }

    private static string ResourceManagerName(string typeNamespace, string className) => $"{typeNamespace}.{className}";

    private static bool IsValidIdentifier(string key) => IdentifierRegex.IsMatch(key);

    private static List<string> CollectLocales(IReadOnlyList<DesignerEntry> entries)
    {
        var set = new HashSet<string>();
        foreach (var e in entries)
            foreach (var l in e.Translations.Keys) set.Add(l);
        var list = set.OrderBy(x => x).ToList();
        if (list.Remove("")) list.Insert(0, "");
        return list;
    }

    private static string PropertyBlock(DesignerEntry entry, string access, IReadOnlyList<string> locales)
    {
        var sb = new StringBuilder();
        foreach (var l in locales)
        {
            if (entry.Translations.TryGetValue(l, out var v) && !string.IsNullOrEmpty(v))
                sb.AppendLine($"        /// <summary>{EscapeXml(v)} ({LocaleLabel(l)})</summary>");
        }
        sb.AppendLine($"        {access} static string {entry.Key} {{");
        sb.AppendLine($"            get {{ return ResourceManager.GetString(\"{entry.Key}\", resourceCulture); }}");
        sb.AppendLine("        }");
        return sb.ToString();
    }

    private static string LocaleLabel(string locale) => string.IsNullOrEmpty(locale) ? "Neutral" : locale;
    private static string EscapeXml(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static string SanitizeIdentifier(string input)
    {
        var cleaned = Regex.Replace(input, @"[^a-zA-Z0-9_]", "");
        if (string.IsNullOrEmpty(cleaned) || char.IsDigit(cleaned[0])) cleaned = "N" + cleaned;
        return cleaned;
    }

    private static string GuessNamespace(string dir)
    {
        var parts = dir.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        var name = parts.LastOrDefault(p => !string.IsNullOrEmpty(p)) ?? "Resources";
        return SanitizeIdentifier(name);
    }

    private static string? FindCsproj(string startDir)
    {
        var dir = startDir;
        for (var i = 0; i < 10; i++)
        {
            var files = Directory.GetFiles(dir, "*.csproj");
            if (files.Length > 0) return files[0];
            var parent = Directory.GetParent(dir);
            if (parent == null) break;
            dir = parent.FullName;
        }
        return null;
    }

    private static string ParseRootNamespace(string xml, string csprojPath)
    {
        var m = Regex.Match(xml, @"<RootNamespace>([^<]+)</RootNamespace>");
        if (m.Success) return m.Groups[1].Value.Trim();
        return Path.GetFileNameWithoutExtension(csprojPath) ?? "Resources";
    }

    private static string? ParseCustomToolNamespace(string xml, string relFile)
    {
        var escaped = Regex.Escape(relFile.Replace('\\', '/'));
        var m = Regex.Match(xml, $@"<EmbeddedResource\s+[^>]*Include=""{escaped}""[^>]*>[\s\S]*?<CustomToolNamespace>([^<]+)</CustomToolNamespace>", RegexOptions.IgnoreCase);
        return m.Success ? m.Groups[1].Value.Trim() : null;
    }

    private static string RelativePath(string from, string to)
    {
        from = Path.GetFullPath(from).TrimEnd(Path.DirectorySeparatorChar);
        to = Path.GetFullPath(to);
        if (to.StartsWith(from, StringComparison.OrdinalIgnoreCase))
        {
            if (to.Length == from.Length) return ".";
            return to.Substring(from.Length + 1).Replace('\\', '/');
        }
        return to;
    }
}

public sealed class DesignerMeta
{
    public string DesignerPath { get; init; } = "";
    public string ClassName { get; init; } = "";
    public string Namespace { get; init; } = "";
    public bool IsPublic { get; init; }
    public string ResourceBaseName { get; init; } = "";
}
